name: moor_sample
description: Moor

publish_to: 'none'

version: 0.0.1-dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor: ^3.3.1
  #moor_flutter: ^3.1.0
  path_provider: ^1.6.11
  path: ^1.7.0
  sqlite3_flutter_libs: ^0.2.0
  platform_info: ^1.1.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.3.1
  build_runner: ^1.10.2
  grinder: ^0.8.5

flutter:
  uses-material-design: true